POST http://localhost:3333/api/links
Content-Type: application/json
# add new link

{
  "code": "ana",
  "url": "https://rocketseat.com.br"
}

###
# list all
GET http://localhost:3333/api/links

###
# list for code "?" and redirect to "https://rocketseat.com.br"
GET http://localhost:3333/marcio

###
# list metric of links visited
GET http://localhost:3333/api/metrics